<?php
session_start();
require_once '../config/database.php';
require_once '../includes/functions.php';

// Check if user is admin
if (!isLoggedIn() || !isAdmin($conn)) {
    header('Location: ../login.php');
    exit();
}

// Get booking ID from URL
$booking_id = isset($_GET['booking_id']) ? (int)$_GET['booking_id'] : 0;

if ($booking_id <= 0) {
    die('Invalid booking ID');
}

// Get booking details with user and vehicle information
$booking_query = "
SELECT b.*, u.username, u.email, u.first_name, u.last_name, u.phone,
       v.name as vehicle_name, v.image_url, v.rate_per_day,
       v.vehicle_type, v.description as vehicle_description
FROM bookings b
JOIN users u ON b.user_id = u.id
JOIN vehicles v ON b.vehicle_id = v.id
WHERE b.id = ?
";

$stmt = mysqli_prepare($conn, $booking_query);
mysqli_stmt_bind_param($stmt, "i", $booking_id);
mysqli_stmt_execute($stmt);
$result = mysqli_stmt_get_result($stmt);
$booking = mysqli_fetch_assoc($result);

if (!$booking) {
    die('Booking not found');
}

// Include TCPDF library
if (!file_exists('../tcpdf/tcpdf.php')) {
    // Redirect to HTML version if TCPDF is not available
    header('Location: generate_invoice_html.php?booking_id=' . $booking_id);
    exit();
}
require_once('../tcpdf/tcpdf.php');

// Create new PDF document
class ADMINPDF extends TCPDF {
    public function Header() {
        // Logo
        $image_file = '../assets/images/MG Logo.jpg';
        if (file_exists($image_file)) {
            $this->Image($image_file, 10, 10, 30, 0, 'JPG', '', 'T', false, 300, '', false, false, 0, false, false, false);
        }
        
        // Set font
        $this->SetFont('helvetica', 'B', 20);
        
        // Title
        $this->Cell(0, 15, 'MG Transport Services', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->Ln();
        $this->SetFont('helvetica', '', 12);
        $this->Cell(0, 10, 'Admin Invoice', 0, false, 'C', 0, '', 0, false, 'M', 'M');
        $this->Ln(20);
    }
    
    public function Footer() {
        // Position at 15 mm from bottom
        $this->SetY(-15);
        // Set font
        $this->SetFont('helvetica', 'I', 8);
        // Page number
        $this->Cell(0, 10, 'Page '.$this->getAliasNumPage().'/'.$this->getAliasNbPages(), 0, false, 'C', 0, '', 0, false, 'T', 'M');
    }
}

// Create new PDF document
$pdf = new ADMINPDF(PDF_PAGE_ORIENTATION, PDF_UNIT, PDF_PAGE_FORMAT, true, 'UTF-8', false);

// Set document information
$pdf->SetCreator('MG Transport Services');
$pdf->SetAuthor('MG Transport Services - Admin');
$pdf->SetTitle('Admin Invoice #' . $booking['id']);
$pdf->SetSubject('Admin Booking Invoice');

// Set default header data
$pdf->SetHeaderData(PDF_HEADER_LOGO, PDF_HEADER_LOGO_WIDTH, PDF_HEADER_TITLE, PDF_HEADER_STRING);

// Set header and footer fonts
$pdf->setHeaderFont(Array(PDF_FONT_NAME_MAIN, '', PDF_FONT_SIZE_MAIN));
$pdf->setFooterFont(Array(PDF_FONT_NAME_DATA, '', PDF_FONT_SIZE_DATA));

// Set default monospaced font
$pdf->SetDefaultMonospacedFont(PDF_FONT_MONOSPACED);

// Set margins
$pdf->SetMargins(PDF_MARGIN_LEFT, PDF_MARGIN_TOP, PDF_MARGIN_RIGHT);
$pdf->SetHeaderMargin(PDF_MARGIN_HEADER);
$pdf->SetFooterMargin(PDF_MARGIN_FOOTER);

// Set auto page breaks
$pdf->SetAutoPageBreak(TRUE, PDF_MARGIN_BOTTOM);

// Set image scale factor
$pdf->setImageScale(PDF_IMAGE_SCALE_RATIO);

// Set font
$pdf->SetFont('helvetica', '', 10);

// Add a page
$pdf->AddPage();

// Calculate days
$start_date = new DateTime($booking['start_date']);
$end_date = new DateTime($booking['end_date']);
$days = $start_date->diff($end_date)->days + 1;

// Calculate GST
$gst_rate = getSystemSetting('gst_rate', $conn);
$gst_amount = ($booking['total_amount'] * $gst_rate) / 100;
$subtotal = $booking['total_amount'] - $gst_amount;

// Get payment details if available
$payment_details = [];
if (!empty($booking['payment_details'])) {
    $payment_details = json_decode($booking['payment_details'], true);
}

// Invoice content
$html = '
<table cellpadding="5" cellspacing="0" style="width: 100%; border: 1px solid #ddd;">
    <tr style="background-color: #f8f9fa;">
        <td colspan="2" style="border: 1px solid #ddd;">
            <strong>Admin Invoice Details</strong>
        </td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd; width: 30%;"><strong>Invoice Number:</strong></td>
        <td style="border: 1px solid #ddd;">INV-' . str_pad($booking['id'], 6, '0', STR_PAD_LEFT) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Invoice Date:</strong></td>
        <td style="border: 1px solid #ddd;">' . date('F d, Y', strtotime($booking['created_at'])) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Generated By:</strong></td>
        <td style="border: 1px solid #ddd;">Admin - ' . date('F d, Y g:i A') . '</td>
    </tr>
</table>

<br><br>

<table cellpadding="5" cellspacing="0" style="width: 100%; border: 1px solid #ddd;">
    <tr style="background-color: #f8f9fa;">
        <td colspan="2" style="border: 1px solid #ddd;">
            <strong>Customer Information</strong>
        </td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd; width: 30%;"><strong>Customer ID:</strong></td>
        <td style="border: 1px solid #ddd;">' . $booking['user_id'] . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Name:</strong></td>
        <td style="border: 1px solid #ddd;">' . htmlspecialchars($booking['first_name'] . ' ' . $booking['last_name']) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Username:</strong></td>
        <td style="border: 1px solid #ddd;">' . htmlspecialchars($booking['username']) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Email:</strong></td>
        <td style="border: 1px solid #ddd;">' . htmlspecialchars($booking['email']) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Phone:</strong></td>
        <td style="border: 1px solid #ddd;">' . htmlspecialchars($booking['phone']) . '</td>
    </tr>
</table>

<br><br>

<table cellpadding="5" cellspacing="0" style="width: 100%; border: 1px solid #ddd;">
    <tr style="background-color: #f8f9fa;">
        <td colspan="2" style="border: 1px solid #ddd;">
            <strong>Booking Details</strong>
        </td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd; width: 30%;"><strong>Booking ID:</strong></td>
        <td style="border: 1px solid #ddd;">' . $booking['id'] . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Vehicle ID:</strong></td>
        <td style="border: 1px solid #ddd;">' . $booking['vehicle_id'] . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Vehicle:</strong></td>
        <td style="border: 1px solid #ddd;">' . htmlspecialchars($booking['vehicle_name']) . ' (' . htmlspecialchars($booking['vehicle_type']) . ')</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Pickup Date:</strong></td>
        <td style="border: 1px solid #ddd;">' . date('F d, Y', strtotime($booking['start_date'])) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Return Date:</strong></td>
        <td style="border: 1px solid #ddd;">' . date('F d, Y', strtotime($booking['end_date'])) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Duration:</strong></td>
        <td style="border: 1px solid #ddd;">' . $days . ' day(s)</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Status:</strong></td>
        <td style="border: 1px solid #ddd;">' . ucfirst($booking['status']) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Payment Method:</strong></td>
        <td style="border: 1px solid #ddd;">' . ucfirst($booking['payment_method']) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Payment Status:</strong></td>
        <td style="border: 1px solid #ddd;">' . ucfirst($booking['payment_status']) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;"><strong>Created At:</strong></td>
        <td style="border: 1px solid #ddd;">' . date('F d, Y g:i A', strtotime($booking['created_at'])) . '</td>
    </tr>
</table>';

// Add payment details if available
if (!empty($payment_details)) {
    $html .= '
    <br><br>
    <table cellpadding="5" cellspacing="0" style="width: 100%; border: 1px solid #ddd;">
        <tr style="background-color: #f8f9fa;">
            <td colspan="2" style="border: 1px solid #ddd;">
                <strong>Payment Details</strong>
            </td>
        </tr>';
    
    foreach ($payment_details as $key => $value) {
        $html .= '
        <tr>
            <td style="border: 1px solid #ddd; width: 30%;"><strong>' . ucfirst(str_replace('_', ' ', $key)) . ':</strong></td>
            <td style="border: 1px solid #ddd;">' . htmlspecialchars($value) . '</td>
        </tr>';
    }
    
    $html .= '</table>';
}

$html .= '
<br><br>

<table cellpadding="5" cellspacing="0" style="width: 100%; border: 1px solid #ddd;">
    <tr style="background-color: #f8f9fa;">
        <td colspan="4" style="border: 1px solid #ddd;">
            <strong>Item Details</strong>
        </td>
    </tr>
    <tr style="background-color: #f8f9fa;">
        <td style="border: 1px solid #ddd; width: 40%;"><strong>Description</strong></td>
        <td style="border: 1px solid #ddd; width: 20%;"><strong>Rate</strong></td>
        <td style="border: 1px solid #ddd; width: 20%;"><strong>Days</strong></td>
        <td style="border: 1px solid #ddd; width: 20%;"><strong>Amount</strong></td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd;">' . htmlspecialchars($booking['vehicle_name']) . ' (' . htmlspecialchars($booking['vehicle_type']) . ')</td>
        <td style="border: 1px solid #ddd;">' . formatCurrency($booking['rate_per_day']) . '</td>
        <td style="border: 1px solid #ddd;">' . $days . '</td>
        <td style="border: 1px solid #ddd;">' . formatCurrency($booking['rate_per_day'] * $days) . '</td>
    </tr>
</table>

<br><br>

<table cellpadding="5" cellspacing="0" style="width: 100%; border: 1px solid #ddd;">
    <tr style="background-color: #f8f9fa;">
        <td colspan="2" style="border: 1px solid #ddd;">
            <strong>Payment Summary</strong>
        </td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd; width: 70%; text-align: right;"><strong>Subtotal:</strong></td>
        <td style="border: 1px solid #ddd; width: 30%;">' . formatCurrency($subtotal) . '</td>
    </tr>
    <tr>
        <td style="border: 1px solid #ddd; text-align: right;"><strong>GST (' . $gst_rate . '%):</strong></td>
        <td style="border: 1px solid #ddd;">' . formatCurrency($gst_amount) . '</td>
    </tr>
    <tr style="background-color: #f8f9fa;">
        <td style="border: 1px solid #ddd; text-align: right;"><strong>Total Amount:</strong></td>
        <td style="border: 1px solid #ddd;"><strong>' . formatCurrency($booking['total_amount']) . '</strong></td>
    </tr>
</table>

<br><br>

<table cellpadding="5" cellspacing="0" style="width: 100%; border: 1px solid #ddd;">
    <tr style="background-color: #f8f9fa;">
        <td colspan="2" style="border: 1px solid #ddd;">
            <strong>Admin Notes</strong>
        </td>
    </tr>
    <tr>
        <td colspan="2" style="border: 1px solid #ddd;">
            <ul>
                <li>This is an administrative invoice for internal use</li>
                <li>Customer ID: ' . $booking['user_id'] . '</li>
                <li>Booking ID: ' . $booking['id'] . '</li>
                <li>Generated on: ' . date('F d, Y g:i A') . '</li>
                <li>For any queries, contact the system administrator</li>
            </ul>
        </td>
    </tr>
</table>

<br><br>

<div style="text-align: center; color: #666; font-size: 10px;">
    <p>MG Transport Services - Administrative Invoice</p>
    <p>This is a computer-generated invoice for administrative purposes.</p>
</div>
';

// Print text using writeHTMLCell()
$pdf->writeHTML($html, true, false, true, false, '');

// Close and output PDF document
$pdf->Output('Admin-Invoice-' . str_pad($booking['id'], 6, '0', STR_PAD_LEFT) . '.pdf', 'I');
?> 